[package]
name = "simple-wasi-pipe"
version = "0.1.0"
edition = "2021"
keywords = ["wasi", "wasm", "pipe"]
description = "wasi unix pipeline"
license = "MIT"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
wasmtime = "0.36.0"
wasmtime-wasi = "0.36.0"
wasi-common = "0.36.0"
serde_json = "1.0.79"
serde = {version="1.0.136", features=["derive"]}
